### ISSUE TITLE
Stored passwords with spaces in

### ISSUE THREAD

**Issue by w4** [MatthewWest/pass-alfred#4]
```
~                                                                              
▶ pass -c Shopping/Papa Johns
Error: Shopping/Papa is not in the password store.
```

Spaces need to be escaped

```
~                                                                             ⍉
▶ pass -c Shopping/Papa\ Johns 
gpg: Note: key has been revoked
Copied Shopping/Papa Johns to clipboard. Will clear in 45 seconds.
```

**Comment by MatthewWest** [comment]
I've got an update prepared which fixes this issue, I'll push it as soon as I'm back to internet.

**Comment by MatthewWest** [comment]
That said, I recommend avoiding spaces in password names, as it doesn't have a particularly nice interface on the command line and i don't want to encourage behaviors which won't work well on the command line. Therefore, the forthcoming update adds support for spaces in password titles everywhere except when adding a new password. I recommend CamelCase.

**Comment by MatthewWest** [comment]
Closed with https://github.com/MatthewWest/pass-alfred/commit/1094748c4cf4b1da40fe824bc82b139d712b42cb
