### ISSUE TITLE
'ascii' codec can't decode byte 0xcf in position 11: ordinal not in range(128)

### ISSUE THREAD

**Issue by bergercookie** [MatthewWest/pass-alfred#5]
I tried using the workflow using both the packal version as well as the latest version by cloning the git repository. Every query that I made ended up in the same error message.

![screen shot 2016-07-31 at 20 44 20](https://cloud.githubusercontent.com/assets/5816719/17278215/44f8a15e-5760-11e6-8a3b-0a7c83766389.png)

**Comment by MatthewWest** [comment]
I'm trying to reproduce your issue. Could you please list the output of the following commands from Terminal or iTerm:
- `/usr/bin/env python --version`
- `uname -a`

In Alfred, open the workflows tab, select _pass_, and click the Bug icon in the upper right. Try running the workflow, and copy-paste the output of the debug console.

Thanks!

**Comment by bergercookie** [comment]
After installing the latest version of pass it seems to be working properly,

Thanks.
