### ISSUE TITLE
where to install new version of pass.py

### ISSUE THREAD

**Issue by academikuser** [MatthewWest/pass-alfred#8]
Hi, I want to use the new "works w/ nested" version.  I can't find pass.py in `~/Library/Application\ Support/Alfred3`   or anywhere else.  I am using the packal version.

**Comment by MatthewWest** [comment]
I just updated the packal version. Sorry it took a bit to get the change pushed.

If you want to install it manually, the location of the workflow depends on whether you're using Dropbox syncing. If you are, it'll be in `~/Dropbox/Alfred\ Settings/Alfred.alfredpreferences/workflows/user.workflow.[some long hash]/pass.py`. You can navigate to it by right clicking the workflow in Alfred Preferences and clicking "Open in Finder".
